create extension if not exists "pgcrypto";

create type public.person_type as enum ('adult','child');
create type public.household_role as enum ('owner','adult','child','viewer');
create type public.task_status as enum ('todo','doing','done','cancelled');
create type public.task_priority as enum ('low','normal','important');
create type public.inbox_status as enum ('inbox','processed','archived');
create type public.sensitivity_level as enum ('normal','sensitive','high');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '', timezone text not null default 'Europe/Berlin', locale text not null default 'en',
  week_starts_on smallint not null default 1 check (week_starts_on between 0 and 6), weekly_reset_day smallint not null default 0 check (weekly_reset_day between 0 and 6),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.households (id uuid primary key default gen_random_uuid(), name text not null, owner_user_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.people (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, type public.person_type not null, first_name text not null, last_name text, birthday date, avatar_path text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.household_members (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, person_id uuid references public.people(id) on delete cascade, role public.household_role not null, created_at timestamptz not null default now(), check ((user_id is not null) <> (person_id is not null)));
create unique index household_member_user_unique on public.household_members(household_id,user_id) where user_id is not null;
create table public.life_areas (id uuid primary key default gen_random_uuid(), household_id uuid references public.households(id) on delete cascade, slug text not null, name text not null, color_token text not null, icon text not null, sort_order integer not null default 0, enabled boolean not null default true);
create table public.inbox_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, household_id uuid not null references public.households(id) on delete cascade, raw_text text not null, suggested_type text, status public.inbox_status not null default 'inbox', captured_at timestamptz not null default now(), processed_at timestamptz);
create table public.goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, life_area_id uuid references public.life_areas(id), horizon text not null check (horizon in ('month','quarter','year','three_year','someday')), title text not null, why text, desired_state text, target_date date, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, life_area_id uuid references public.life_areas(id), goal_id uuid references public.goals(id) on delete set null, title text not null, outcome text not null, status text not null default 'active', starts_on date, target_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, creator_user_id uuid not null references auth.users(id), assignee_person_id uuid references public.people(id), life_area_id uuid references public.life_areas(id), project_id uuid references public.projects(id), title text not null, notes text, status public.task_status not null default 'todo', priority public.task_priority not null default 'normal', due_date date, due_at timestamptz, duration_minutes integer check (duration_minutes > 0), is_essential boolean not null default false, source_inbox_item_id uuid references public.inbox_items(id), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.task_recurrences (id uuid primary key default gen_random_uuid(), task_id uuid not null unique references public.tasks(id) on delete cascade, rrule text not null, timezone text not null default 'Europe/Berlin', next_occurrence timestamptz);
create table public.daily_outcomes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, date date not null, slot text not null check (slot in ('one','two','three')), life_area_id uuid references public.life_areas(id), title text not null, notes text, task_id uuid references public.tasks(id), progress integer not null default 0 check (progress between 0 and 100), status text not null default 'active', unique(user_id,date,slot));
create table public.events (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, person_id uuid references public.people(id), title text not null, description text, starts_at timestamptz not null, ends_at timestamptz not null, all_day boolean not null default false, location text, source text not null default 'internal', external_id text, created_at timestamptz not null default now(), check(ends_at >= starts_at));
create table public.routines (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, life_area_id uuid references public.life_areas(id), title text not null, ideal_description text, minimum_description text, rrule text not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.routine_logs (id uuid primary key default gen_random_uuid(), routine_id uuid not null references public.routines(id) on delete cascade, date date not null, status text not null check(status in ('full','minimum','skipped','not_needed')), notes text, unique(routine_id,date));
create table public.checkins (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, date date not null, energy smallint check(energy between 1 and 5), mood text, sleep_hours numeric check(sleep_hours between 0 and 24), movement_minutes integer check(movement_minutes >= 0), protected_minutes integer check(protected_minutes >= 0), notes text, unique(user_id,date));
create table public.meal_plans (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, date date not null, meal_type text not null, title text not null, recipe_url text, notes text);
create table public.grocery_lists (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, status text not null default 'active');
create table public.grocery_items (id uuid primary key default gen_random_uuid(), list_id uuid not null references public.grocery_lists(id) on delete cascade, title text not null, quantity text, section text, store text, checked boolean not null default false);
create table public.learning_programs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, category text not null, provider text, target text, status text not null default 'active', starts_on date, ends_on date, weekly_minutes_goal integer check(weekly_minutes_goal >= 0));
create table public.learning_sessions (id uuid primary key default gen_random_uuid(), program_id uuid not null references public.learning_programs(id) on delete cascade, session_date date not null, focus text not null, planned_minutes integer not null check(planned_minutes > 0), actual_minutes integer check(actual_minutes >= 0), confidence smallint check(confidence between 1 and 5), notes text);
create table public.career_timeline (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, type text not null, title text not null, organization text, starts_on date not null, ends_on date, description text, professional_narrative text);
create table public.evidence_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, timeline_id uuid references public.career_timeline(id) on delete set null, title text not null, type text not null, description text, skills_summary text, occurred_on date, file_path text, external_url text, visibility text not null default 'private' check(visibility in ('private','portfolio')));
create table public.portfolio_projects (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, challenge text, objective text, role text, approach text, tools text, outcome text, metrics text, lessons text, status text not null default 'draft');
create table public.financial_items (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, title text not null, category text not null, amount_cents bigint not null check(amount_cents >= 0), currency text not null default 'EUR', frequency text not null, due_date date, next_due_at timestamptz, status text not null default 'upcoming', notes text);
create table public.documents (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, owner_person_id uuid references public.people(id), uploaded_by_user_id uuid not null references auth.users(id), title text not null, category text not null, issuer text, issue_date date, expiry_date date, storage_path text not null, mime_type text not null, size_bytes bigint not null check(size_bytes > 0 and size_bytes <= 20971520), sensitivity public.sensitivity_level not null default 'sensitive', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reminders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, entity_type text not null, entity_id uuid not null, scheduled_at timestamptz not null, channel text not null check(channel in ('in_app','email','push')), status text not null default 'scheduled');
create table public.notification_preferences (user_id uuid primary key references auth.users(id) on delete cascade, quiet_hours_start time, quiet_hours_end time, category_toggles jsonb not null default '{}', daily_digest boolean not null default false, weekly_digest boolean not null default true);
create table public.audit_events (id bigint generated always as identity primary key, user_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id uuid, created_at timestamptz not null default now(), metadata jsonb not null default '{}');

create or replace function public.is_household_member(target_household uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.household_members hm where hm.household_id=target_household and hm.user_id=auth.uid()) or exists(select 1 from public.households h where h.id=target_household and h.owner_user_id=auth.uid()) $$;
create or replace function public.is_household_owner(target_household uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.households h where h.id=target_household and h.owner_user_id=auth.uid()) $$;

alter table public.profiles enable row level security; alter table public.households enable row level security; alter table public.household_members enable row level security; alter table public.people enable row level security; alter table public.life_areas enable row level security; alter table public.inbox_items enable row level security; alter table public.tasks enable row level security; alter table public.task_recurrences enable row level security; alter table public.daily_outcomes enable row level security; alter table public.events enable row level security; alter table public.routines enable row level security; alter table public.routine_logs enable row level security; alter table public.checkins enable row level security; alter table public.meal_plans enable row level security; alter table public.grocery_lists enable row level security; alter table public.grocery_items enable row level security; alter table public.learning_programs enable row level security; alter table public.learning_sessions enable row level security; alter table public.career_timeline enable row level security; alter table public.evidence_items enable row level security; alter table public.portfolio_projects enable row level security; alter table public.financial_items enable row level security; alter table public.documents enable row level security; alter table public.goals enable row level security; alter table public.projects enable row level security; alter table public.reminders enable row level security; alter table public.notification_preferences enable row level security; alter table public.audit_events enable row level security;

create policy "own profile" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "household member access" on public.households for select using(public.is_household_member(id)); create policy "create household" on public.households for insert with check(owner_user_id=auth.uid()); create policy "owner manages household" on public.households for update using(public.is_household_owner(id)) with check(owner_user_id=auth.uid());
create policy "members visible" on public.household_members for select using(public.is_household_member(household_id)); create policy "owner manages members" on public.household_members for all using(public.is_household_owner(household_id)) with check(public.is_household_owner(household_id));
create policy "people household access" on public.people for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id));
create policy "life areas household access" on public.life_areas for all using(household_id is null or public.is_household_member(household_id)) with check(public.is_household_member(household_id));
create policy "own inbox" on public.inbox_items for all using(user_id=auth.uid()) with check(user_id=auth.uid() and public.is_household_member(household_id));
create policy "household tasks" on public.tasks for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id) and creator_user_id=auth.uid());
create policy "own outcomes" on public.daily_outcomes for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own checkins" on public.checkins for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own goals" on public.goals for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own reminders" on public.reminders for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own preferences" on public.notification_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "household events" on public.events for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id)); create policy "household routines" on public.routines for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id)); create policy "household meals" on public.meal_plans for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id)); create policy "household groceries" on public.grocery_lists for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id)); create policy "household finances" on public.financial_items for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id)); create policy "household projects" on public.projects for all using(public.is_household_member(household_id)) with check(public.is_household_member(household_id) and user_id=auth.uid());
create policy "private documents" on public.documents for select using((sensitivity <> 'high' and public.is_household_member(household_id)) or uploaded_by_user_id=auth.uid()); create policy "upload documents" on public.documents for insert with check(uploaded_by_user_id=auth.uid() and public.is_household_member(household_id)); create policy "uploader manages documents" on public.documents for update using(uploaded_by_user_id=auth.uid()) with check(uploaded_by_user_id=auth.uid()); create policy "uploader deletes documents" on public.documents for delete using(uploaded_by_user_id=auth.uid());
create policy "own learning programs" on public.learning_programs for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own career timeline" on public.career_timeline for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own evidence" on public.evidence_items for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own portfolio" on public.portfolio_projects for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "task recurrence through task" on public.task_recurrences for all using(exists(select 1 from public.tasks t where t.id=task_id and public.is_household_member(t.household_id))) with check(exists(select 1 from public.tasks t where t.id=task_id and public.is_household_member(t.household_id)));
create policy "routine logs through routine" on public.routine_logs for all using(exists(select 1 from public.routines r where r.id=routine_id and public.is_household_member(r.household_id))) with check(exists(select 1 from public.routines r where r.id=routine_id and public.is_household_member(r.household_id)));
create policy "grocery items through list" on public.grocery_items for all using(exists(select 1 from public.grocery_lists g where g.id=list_id and public.is_household_member(g.household_id))) with check(exists(select 1 from public.grocery_lists g where g.id=list_id and public.is_household_member(g.household_id)));
create policy "sessions through program" on public.learning_sessions for all using(exists(select 1 from public.learning_programs p where p.id=program_id and p.user_id=auth.uid())) with check(exists(select 1 from public.learning_programs p where p.id=program_id and p.user_id=auth.uid()));
create policy "own audit log" on public.audit_events for select using(user_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('avatars','avatars',false,5242880,array['image/jpeg','image/png','image/webp']),
('documents-private','documents-private',false,20971520,array['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document']),
('career-evidence-private','career-evidence-private',false,20971520,array['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document']),
('memories-private','memories-private',false,10485760,array['image/jpeg','image/png','image/webp']);

create policy "owners read own storage" on storage.objects for select using(bucket_id in ('avatars','documents-private','career-evidence-private','memories-private') and (storage.foldername(name))[1]=auth.uid()::text);
create policy "owners upload own storage" on storage.objects for insert with check(bucket_id in ('avatars','documents-private','career-evidence-private','memories-private') and (storage.foldername(name))[1]=auth.uid()::text);
create policy "owners delete own storage" on storage.objects for delete using(bucket_id in ('avatars','documents-private','career-evidence-private','memories-private') and (storage.foldername(name))[1]=auth.uid()::text);
